### ISSUE TITLE
When QueryStirng param is Int type,values such as 1000018, do request will convert to 1.000018e+06

### ISSUE THREAD

**Issue by lvxuan263** [wenerme/go-req#2]
An incorrect conversion will cause the request to fail.

**Comment by wenerme** [comment]
@lvxuan263 can you give a Req demo , which QueryString you are reference to ?

**Comment by lvxuan263** [comment]
`
package wecom

import (
	"github.com/wenerme/go-req"
	gowecom "github.com/wenerme/go-wecom/wecom"
)

type GetAgentRequest struct {
	gowecom.GetAgentRequest
	AgentID string `json:"agentid"`
}

func GetAgent(r *GetAgentRequest, opts ...interface{}) (out gowecom.GetAgentResponse, err error) {
	err = appClient.Request.With(req.Request{
		Method: "GET",
		URL:    "/cgi-bin/agent/get",
		**Query:  r,**
	}).Fetch(&out)
	return
}
`
gowecom.GetAgentRequest 中的agentid为int类型，在req.Request 设置为QueryString Param后，发请求时会被转换为字符串 "1.000018e+06"，导致企微接口报错。我之前临时把agentid覆盖成string类型，保证请求成功
